version: '3.5'
services:
  go:
    container_name: go
    image: golang:1.10-alpine
    volumes:
      - ./data/go:/go/src
      - ./go/bin/startup.sh:/go/startup.sh
    tty: true
    command: ./startup.sh
    entrypoint: ash
    depends_on:
      - mongo
    restart: always

  mongo:
    container_name: mongo
    image: mongo:3.6
    volumes:
      - mongo-data:/data/db
    command: "--auth"
    restart: always

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./data:/var/www/html
    depends_on:
      - php
      - go
    restart: always

  mysql:
    container_name: mysql
    image: mysql:5.7.21
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    restart: always

  php:
    container_name: php
    build: ./php
    volumes:
      - ./data:/var/www/html
    depends_on:
      - mysql
    restart: always

volumes:
  db-data:
    driver: local
  mongo-data:
    driver: local
